import { Metadata } from 'next'

type ToutiaoTopSearch = {
  data: { words: WordType[] }[]
}

type WordType = {
  word: string
}

function getHotSearch() {
  return fetch('https://is-lq.snssdk.com/api/suggest_words/?business_id=10016')
    .then<ToutiaoTopSearch>(res => res.json())
    .then(({ data }) => {
      return data.map(c => c.words).flat(1)
    })
}

export const revalidate = 0

export const metadata: Metadata = {
  title: '头条-HoTop',
  description: 'Generated by create next app',
}

export default async function Home() {
  const data = await getHotSearch()
  return (
    <div className="flow-root p-2">
      <dl className="-my-3 divide-y divide-gray-100 text-sm">
        {data.map((item: WordType, index: number) => (
          <div key={index} className="grid grid-cols-1 gap-1 py-3 sm:grid-cols-3 sm:gap-4">
            <dt className="font-medium text-gray-900 flex gap-1 items-center">{item.word}</dt>
          </div>
        ))}
      </dl>
    </div>
  )
}
