import { Metadata } from 'next'

type DouyinTopSearch = {
  data: {
    trending_list: WordType[]
    word_list: WordType[]
  }
}

type WordType = {
  word: string
}

function getHotSearch() {
  return fetch('https://aweme-lq.snssdk.com/aweme/v1/hot/search/list/')
    .then<DouyinTopSearch>(res => res.json())
    .then(({ data }) => {
      return data.trending_list.concat(data.word_list)
    })
}

export const revalidate = 0

export const metadata: Metadata = {
  title: '抖音-HoTop',
  description: 'Generated by create next app',
}

export default async function Home() {
  const data = await getHotSearch()
  return (
    <div className="flow-root p-2">
      <dl className="-my-3 divide-y divide-gray-100 text-sm">
        {data.map((item: WordType, index: number) => (
          <div key={index} className="grid grid-cols-1 gap-1 py-3 sm:grid-cols-3 sm:gap-4">
            <dt className="font-medium text-gray-900 flex gap-1 items-center">
              {item.word}
              {/* <span className="whitespace-nowrap rounded-full bg-green-100 px-2.5 py-0.5 text-sm text-green-600">
                {item.category}
              </span> */}
            </dt>
          </div>
        ))}
      </dl>
    </div>
  )
}
