name: schedule

on:
  workflow_dispatch:
  schedule:
    - cron: "0,30 * * * *"
  push:
    branches:
      - dev # 只在 dev 分支上运行

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run Command
        run: pnpm start

      - name: Commit Files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit --allow-empty -m "实时更新微博热搜"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Purge Jsdelivr
        run: |
          curl "https://purge.jsdelivr.net/gh/sunven/hotop@dev/api/$(date +%Y-%m-%d).json"
